version: 0.0
os: linux

files:
  - source: ROOT.war
    destination: /opt/tomcat9/webapps/

hooks:
  BeforeInstall:
      - location: scripts/before_install.sh
        timeout: 300
        runas: ec2-user

  ApplicationStart:
    - location: scripts/start_tomcat.sh
      timeout: 300
      runas: ec2-user
