version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies...
      - mvn --version

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install

  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p output/scripts
      - cp target/followme.war output/ROOT.war
      - cp appspec.yml output/
      - cp scripts/*.sh output/scripts/

artifacts:
  files:
    - output/**
  discard-paths: no
  name: ROOT
