version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies...
      - mvn --version

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install

  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p output/scripts
      - echo "== [scripts 디렉토리 내용] =="
      - ls -al scripts/
      - cp scripts/*.sh output/scripts/ || echo "No script files found"
      - echo "== [output/scripts 복사 결과] =="
      - ls -al output/scripts/

artifacts:
  files:
    - output/ROOT.war
    - output/appspec.yml
    - output/scripts/**
  discard-paths: no
  name: ROOT
